name: E2E Performance Testing
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  k6-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install k6
        uses: grafana/setup-k6-action@v1
        with:
          k6-version: "0.49.0"

      - name: Lanuch server
        run: |
          docker compose up -d --build
          npx wait-port http://localhost:3000/health -t 30000

      - name: Run Performance tests
        uses: grafana/run-k6-action@v1
        with:
          path: tests-k6/test.js
          flags: --out json=tests-k6/k6-results.json

      - name: Upload results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: k6-results
          path: tests-k6/k6-results.json